dist: trusty
language: node_js
node_js:
  - "11"
cache: npm
sudo: required
branches:
  only:
  - master
  - develop
  - /^feature\/.*/
  - /^release-.*/
  - /^hotfix-.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
script:
  - npm run test
